### ISSUE TITLE
setting redirectURI in Keycloak for the client 'example-react-router' (example project React Router)

### ISSUE THREAD

**Issue by martin617github** [keycloakify/oidc-spa#35]
Hello!

First of all, thanks for the oidc-spa example projects, demonstrating integration with Tanstack or React Router. I have the React Router example running now, and it seems to be running fine :-)

However, one topic took me quite some time: the client settings in Keycloak.
Perhaps I was overlooking some documentation? For a large extend, the client settings in Keycloak are obvious, but the "*" (the wildcard) in the redirectURIs took me almost two hours.

![image](https://github.com/user-attachments/assets/489809bd-f55a-4b6a-83ca-812bba7d353c)

I write it here, for others to know. 
Best regards.

**Comment by garronej** [comment]
Hello @martin617github,  

Thanks for sharing your solution.  

However I'm a bit surprised because:  
1) oidc-spa is supposed to give you a clear error message to let you know what you need to fix in the Keycloak configuration.  
2) There's a documentation on how to setup keycloak https://docs.oidc-spa.dev/resources/usage-with-keycloak  


Let me know if you think that thoses resources need to be updated.

**Comment by martinDevo** [comment]
Hello @garronej 

Short reply on your response, and thanks for your quick reaction :-)

1. It only took a little effort to reproduce the error so that you can see it, here it is.
What I did is put the Valid redirect URIs in Keycloak back to **http://localhost:5173** (without wildcard). Then what I did is pressing the button 'Login' on the home page of 'OIDC-SPA + React router' (or clicking the link 'My protected page', it doesn't matter)

<img src="https://github.com/user-attachments/assets/cc903146-087f-4140-8536-3526adb39ab5" width="400">

2. I figured out the error-cause from the Keyclock console log, since the example-app appears to start with an initial authorize-attempt to the Keycloak (userId="null") when initializing the home page (and when reloading the home page). The Network tab in the Developer View of the browser is still empty at the initial stage.
  
![image](https://github.com/user-attachments/assets/0d9128b0-3841-4bdd-9e36-d3064f3c624a)

And of course I should have looked better for the documentation resources, but I didn't (my bad). At least I am comfortable that I didn't ask what I could have found myself :-)

My greetings!

**Comment by garronej** [comment]
but if you look at the console it's explained in details what's going on.  

https://docs.oidc-spa.dev/documentation/error-management

**Comment by garronej** [comment]
Example: 

<img width="1857" alt="image" src="https://github.com/user-attachments/assets/7f6c920b-dfe4-4b80-8c60-f409f618359e">

**Comment by martin617github** [comment]
Indeed, here I see it:

![image](https://github.com/user-attachments/assets/092a2f81-01d4-4a7c-bf01-15105e31203c)

I have missed that all the way.

**Comment by martin617github** [comment]
I am happy to close this issue, aren't we?
Thank you!
